# https://www.gitpod.io/docs/references/gitpod-yml
checkoutLocation: "tutorial/sharg-parser"
workspaceLocation: "/tutorial"
tasks:
  - name: Setup
    before: mkdir -p build source
    init: HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_ENV_HINTS=1 brew install cmake gcc@12 tree
    command: echo && echo "GCC 12 available via g++-12" && echo && echo "g++-12 --version" && g++-12 --version
