# https://www.gitpod.io/docs/references/gitpod-yml
checkoutLocation: "tutorial/source/sharg-parser"
workspaceLocation: "/tutorial"
tasks:
  - name: Create Directories
    before: mkdir -p build source
