name: Sharg Markdown

on:
  push:
    branches:
      - 'main'

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -exo pipefail {0}

jobs:
  readme-snippet:
    name: Update README
    concurrency:
      group: readme-snippet-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Checkout Sharg
        uses: actions/checkout@v3

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.SEQAN_ACTIONS_GPG_KEY }}
          passphrase: ${{ secrets.SEQAN_ACTIONS_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      # - name: Update README
      #   uses: dineshsonachalam/markdown-autodocs@v1.0.7
      #   with:
      #     commit_author: seqan-actions[bot] <seqan-actions@users.noreply.github.com>
      #     commit_user_email: seqan-actions@users.noreply.github.com
      #     commit_message: "[MISC] Update README.md"
      #     output_file_paths: '[./README.md]'
      #     categories: '[code-block]'

      - name: Update README
        run: |
          npm i -g doctoc@2.1.0 markdown-autodocs
          wget https://raw.githubusercontent.com/dineshsonachalam/markdown-autodocs/v1.0.7/action.py
          python3 action.py \
            -repo '${{ github.repository }}' \
            -access_token '${{ secrets.SEQAN_ACTIONS_PAT }}' \
            -commit_author 'seqan-actions[bot] <seqan-actions@users.noreply.github.com>' \
            -commit_user_email 'seqan-actions@users.noreply.github.com' \
            -commit_message '[MISC] Update README.md' \
            -branch '${{ github.head_ref }}' \
            -output_file_paths '[./README.md]' \
            -categories '[code-block]'
